services:
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: config-server
    container_name: config-server
    environment:
      GIT_USERNAME: ${GIT_USERNAME}
      GIT_TOKEN: ${GIT_TOKEN}
    ports:
      - "8888:8888"
    networks:
      - internal

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: user-service
    container_name: user-service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      USER_DB_NAME: ${USER_DB_NAME}
      USER_DB_USERNAME: ${USER_DB_USERNAME}
      USER_DB_PASSWORD: ${USER_DB_PASSWORD}
    volumes:
      - ./user-service:/app
      - m2-cache:/root/.m2
    ports:
      - "8001:8001"
    depends_on:
      - config-server
      - user-service-db
    networks:
      - internal

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: product-service
    container_name: product-service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      PRODUCT_DB_NAME: ${PRODUCT_DB_NAME}
      PRODUCT_DB_USERNAME: ${PRODUCT_DB_USERNAME}
      PRODUCT_DB_PASSWORD: ${PRODUCT_DB_PASSWORD}
    volumes:
      - ./product-service:/app
      - m2-cache:/root/.m2
    ports:
      - "8002:8002"
    depends_on:
      - config-server
      - product-service-db
    networks:
      - internal

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    image: order-service
    container_name: order-service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      ORDER_DB_NAME: ${ORDER_DB_NAME}
      ORDER_DB_USERNAME: ${ORDER_DB_USERNAME}
      ORDER_DB_PASSWORD: ${ORDER_DB_PASSWORD}
    volumes:
      - ./order-service:/app
      - m2-cache:/root/.m2
    ports:
      - "8003:8003"
    depends_on:
      - config-server
      - order-service-db
    networks:
      - internal

  user-service-db:
    image: mongodb/mongodb-community-server:8.2.4-ubi8
    container_name: user-service-db
    environment:
      MONGO_INITDB_DATABASE: ${USER_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${USER_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${USER_DB_PASSWORD}
    volumes:
      - user_service_db:/data/db
    networks:
      - internal

  product-service-db:
    image: mysql:8.0
    container_name: product-service-db
    environment:
      MYSQL_DATABASE: ${PRODUCT_DB_NAME}
      MYSQL_USER: ${PRODUCT_DB_USERNAME}
      MYSQL_PASSWORD: ${PRODUCT_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PRODUCT_DB_ROOT_PASSWORD}
    volumes:
      - product_service_db:/var/lib/mysql
    networks:
      - internal

  order-service-db:
    image: postgres:16-alpine
    container_name: order-service-db
    environment:
      POSTGRES_DB: ${ORDER_DB_NAME}
      POSTGRES_USER: ${ORDER_DB_USERNAME}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - order_service_db:/var/lib/postgresql/data
    networks:
      - internal

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: user-service-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${USER_DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${USER_DB_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - "8081:8081"
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin:5.2.3
    container_name: phpmyadmin
    environment:
      PMA_HOST: product-service-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${PRODUCT_DB_ROOT_PASSWORD}
    ports:
      - "8082:80"
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4:9.11.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  user_service_db:
  product_service_db:
  order_service_db:
  pgadmin:
  m2-cache:
