services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.dev.dev.dev.dev.dev
    image: user-service
    container_name: user-service
    env_file:
      - ./user-service/order-service-db.env
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    depends_on:
      - config-server
      - user-service-db
    networks:
      - internal

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile.dev.dev.dev.dev.dev
    image: product-service
    container_name: product-service
    env_file:
      - ./product-service/order-service-db.env
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    depends_on:
      - config-server
      - product-service-db
    networks:
      - internal

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile.dev.dev.dev.dev.dev
    image: order-service
    container_name: order-service
    env_file:
      - ./order-service/order-service-db.env
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    depends_on:
      - config-server
      - order-service-db
    networks:
      - internal

  user-service-db:
    image: mongodb/mongodb-community-server:8.2.4-ubi8
    container_name: user-service-db
    env_file:
      - ./user-service/order-service-db.env
    networks:
      - internal

  product-service-db:
    image: mysql:8.0
    container_name: product-service-db
    env_file:
      - ./product-service/order-service-db.env
    networks:
      - internal

  order-service-db:
    image: postgres:16-alpine
    container_name: order-service-db
    env_file:
      - ./order-service/order-service-db.env
    networks:
      - internal

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    env_file:
      - platform/env/mongo-express.env
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin:5.2.3
    container_name: phpmyadmin
    env_file:
      - platform/env/phpmyadmin.env
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4:9.11.0
    container_name: pgadmin
    env_file:
      - platform/env/pgadmin.env
    networks:
      - internal

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile.dev.dev.dev.dev.dev
    image: config-server
    container_name: config-server
    env_file:
      - ./config-server/order-service-db.env
    networks:
      - internal

  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile.dev.dev.dev.dev.dev
    image: discovery-server
    container_name: discovery-server
    networks:
      - internal

  rabbitmq:
    image: rabbitmq:4.2.3-management
    container_name: rabbitmq
    env_file:
      - platform/env/rabbitmq.env
    networks:
      internal:

networks:
  internal:
    driver: bridge