services:
  rabbitmq:
    image: rabbitmq:4.2.3-management
    container_name: rabbitmq
    env_file:
      - ../env/dev/rabbitmq.env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    env_file:
      - ../env/dev/mongo-express.env
    ports:
      - "8081:8081"
    depends_on:
      - user-service-db
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin:5.2.3
    container_name: phpmyadmin
    env_file:
      - ../env/dev/phpmyadmin.env
    ports:
      - "8082:80"
    depends_on:
      - product-service-db
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4:9.11.0
    container_name: pgadmin
    env_file:
      - ../env/dev/pgadmin.env
    ports:
      - "8083:80"
    depends_on:
      - order-service-db
    networks:
      - internal

  user-service-db:
    image: mongodb/mongodb-community-server:8.2.4-ubi8
    container_name: user-service-db
    volumes:
      - user_service_db:/data/db
    env_file:
      - ../env/dev/user-service-db.env
    ports:
      - "27017:27017"
    networks:
      - internal

  product-service-db:
    image: mysql:8.0
    container_name: product-service-db
    volumes:
      - product_service_db:/var/lib/mysql
    env_file:
      - ../env/dev/product-service-db.env
    ports:
     - "3306:3306"
    networks:
      - internal

  order-service-db:
    image: postgres:16-alpine
    container_name: order-service-db
    volumes:
      - order_service_db:/var/lib/postgresql/data
    env_file:
      - ../env/dev/order-service-db.env
    ports:
      - "5432:5432"
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  user_service_db:
  product_service_db:
  order_service_db:
